# Generated by Django 4.2 on 2023-04-18 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("openapi_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersgroup",
            name="token",
            field=models.CharField(
                default=uuid.UUID("aaf5520a-f836-4f3d-b175-4a74570a9912"),
                editable=False,
                max_length=85,
                unique=True,
                verbose_name="token",
            ),
        ),
    ]
