# Generated by Django 4.2 on 2023-04-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "actionnetwork",
            "0006_remove_signature_campaign_remove_signature_person_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetEmailPressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "email_address",
                    models.EmailField(max_length=254, verbose_name="Email address"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(verbose_name="Created date")),
                (
                    "api_response_json",
                    models.JSONField(verbose_name="API Response JSON"),
                ),
                ("fields", models.JSONField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.campaign",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailPressure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(verbose_name="Created date")),
                (
                    "api_response_json",
                    models.JSONField(verbose_name="API Response JSON"),
                ),
                (
                    "email_subject",
                    models.CharField(max_length=80, verbose_name="Email subject"),
                ),
                ("email_body", models.TextField(verbose_name="Email body")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.campaign",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.person",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(to="openapi_actions.targetemailpressure"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(verbose_name="Created date")),
                (
                    "api_response_json",
                    models.JSONField(verbose_name="API Response JSON"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("creditcard", "Cartão de crédito"),
                            ("boleto", "Boleto"),
                            ("pix", "Pix"),
                        ],
                        max_length=20,
                        verbose_name="Payment method",
                    ),
                ),
                (
                    "is_subscription",
                    models.BooleanField(default=False, verbose_name="Is subscription?"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.campaign",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actionnetwork.person",
                    ),
                ),
            ],
        ),
    ]
